### ISSUE TITLE
log4j warning stops logstash to work

### ISSUE THREAD

**Issue by renevdm** [logstash-plugins/logstash-input-beats#193]
When checking the logstash config, I get this "warning":

```
# service logstash configtest
log4j:WARN No appenders could be found for logger (io.netty.util.internal.logging.InternalLoggerFactory).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
Configuration OK
```

When I start logstash, no events flow into elasticsearch. But when I disable all beats inputs, the error messages disappear and events do flow into elasticsearch.

Yes it's a warning, but when running logstash with beats inputs enabled, logstash stops handling all events. Even stopping logstash doesn't work anymore, it looks like it is really stuck, but shows no errors in the log files. Only way to stop logstash is using a dirty "kill -9"

**Comment by ph** [comment]
What version of Logstash you are running and the version of beats?

```
bin/logstash-plugin list --verbose beats
bin/logstash version
```

**Comment by ph** [comment]
Also if you bump up the error level to debug do you see more information that could explain why logstash is stopped? You can do that with `--log.level debug`

**Comment by renevdm** [comment]
# bin/logstash-plugin list --verbose beats
logstash-input-beats (3.1.8)
# bin/logstash version
logstash 2.4.1

**Comment by ph** [comment]
Ok the beats if a few version behind, I think that the shutdown hang was fixed in part of a newer release wasn't documented.

What your config look like? Usually when the input hangs on shutdown is because it's stuck writing to the queue, so I am wondering if any config or output could cause this.

**Comment by ph** [comment]
lets try upgrading your plugin with `bin/logstash-plugin update logstash-input-beats`

**Comment by renevdm** [comment]
The debug output was waaaaaay too much...  Let's give it a shot with updating the plugin.

```
# bin/logstash-plugin update logstash-input-beats
Updated logstash-input-beats 3.1.8 to 3.1.12
```

**Comment by renevdm** [comment]
Ok, the error message is gone when doing a checkconfig

```
# service logstash configtest
Configuration OK
```

But still logstash stops processing events after running ok for a few seconds...

**Comment by renevdm** [comment]
I now see this appearing in the log, this clearifies why stopping logstash isn't working:

```
{:timestamp=>"2017-02-17T22:25:41.583000+0100", :message=>"The shutdown process appears to be stalled due to busy or blocked plugins. Check the logs for more information.", :level=>:error}
```

**Comment by ph** [comment]
@renevdm Your Logstash configuration and a thread dump with `jstack` might help me to understand what is going on.

**Comment by renevdm** [comment]
I can send you the config files, but I really need some help with jstack as I'm not familiair with that

**Comment by ph** [comment]
@renevdm **jstack** is not too complicated, just grab the *PID* of your Logstash Instance and use the following command.

run `jstack -l <PID> > thread.dump`, gist the thread dump and add the link to this issue.

**Comment by renevdm** [comment]
I sent you an e-mail with the configs, but the jstack is no luck I guess.....

```
# jstack -l 12153 > thread.dump
12153: Unable to open socket file: target process not responding or HotSpot VM not loaded
The -F option can be used when the target process is not responding
# jstack -l 12153 -F > thread.dump
Error attaching to core file: cannot open binary file
sun.jvm.hotspot.debugger.DebuggerException: cannot open binary file
        at sun.jvm.hotspot.debugger.linux.LinuxDebuggerLocal.attach0(Native Method)
        at sun.jvm.hotspot.debugger.linux.LinuxDebuggerLocal.attach(LinuxDebuggerLocal.java:286)
        at sun.jvm.hotspot.HotSpotAgent.attachDebugger(HotSpotAgent.java:673)
        at sun.jvm.hotspot.HotSpotAgent.setupDebuggerLinux(HotSpotAgent.java:611)
        at sun.jvm.hotspot.HotSpotAgent.setupDebugger(HotSpotAgent.java:337)
        at sun.jvm.hotspot.HotSpotAgent.go(HotSpotAgent.java:304)
        at sun.jvm.hotspot.HotSpotAgent.attach(HotSpotAgent.java:156)
        at sun.jvm.hotspot.tools.Tool.start(Tool.java:191)
        at sun.jvm.hotspot.tools.Tool.execute(Tool.java:118)
        at sun.jvm.hotspot.tools.JStack.main(JStack.java:92)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at sun.tools.jstack.JStack.runJStackTool(JStack.java:140)
        at sun.tools.jstack.JStack.main(JStack.java:106)
```

**Comment by ph** [comment]
@renevdm in your configuration, I see in the **beats** critical path a few **grok** filters, I haven't look at the details of your regular expressions, but some expressions can cause a `redos` problems.

In the case of Logstash that would cause the workers to lock and stop processing any events, making it appear that Logstash doesn't process anything. One of the side effects of this problem can be identified with a really high *CPU* usage of Logstash and can make the jstack refuse to dump.

I suggest you try your different beats configurations in isolation with or without your grok to find the problematic one.

A few helpful links:
https://www.elastic.co/blog/do-you-grok-grok
https://en.wikipedia.org/wiki/ReDoS

**Comment by renevdm** [comment]
Ok, thanks. But this config used to work, until I upgraded logstash this week. After the upgrade I got the symptoms as described.
I'll pick this up in the morning again. At least the log4j errors have gone now.
Thanks for your help!

**Comment by ph** [comment]
@renevdm You have upgraded from which version?

**Comment by renevdm** [comment]
I upgraded from 2.4.0 to 2.4.1

**Comment by renevdm** [comment]
I disabled some inputs now and disabled all GeoIP lookups and now it all seems to be working. I think I hit a redo indeed.... Hmmm... It looks like I should really clean up those inputs.

**Comment by ph** [comment]
@renevdm What is the cpu usage went this happen? is jstack able to produce a stack?

**Comment by reswob10** [comment]
I have the same problem as what originally opened this ticket and I still have the issue after upgrading the beats plugin.  

Here is the information about my installation:

Installed via downloading the .rpm and running rpm -i install
Files were downloaded and installed within the past week (since April 28, 2017).

[root@elastic-01 logstash]# cat /etc/*release
CentOS release 6.9 (Final)
[root@elastic-01 logstash]# /usr/share/logstash/bin/logstash --version
logstash 5.4.0
[root@elastic-01 logstash]# /usr/share/logstash/bin/logstash-plugin list --verbose beats
logstash-input-beats (3.1.12)
[root@elastic-01 logstash]# /usr/share/logstash/bin/logstash-plugin update logstash-input-beats
Updating logstash-input-beats
which: no javac in (/usr/lib64/qt-3.3/bin:/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin:/root/bin)
io/console on JRuby shells out to stty for most operations
Updated logstash-input-beats 3.1.12 to 3.1.15


What happens when I try to start logstash with beats:
[root@elastic-01 logstash]# /usr/share/logstash/bin/logstash -f /etc/logstash/conf.d/first-pipeline.conf --path.settings /etc/logstash
Sending Logstash's logs to /var/log/logstash which is now configured via log4j2.properties
log4j:WARN No appenders could be found for logger (io.netty.util.internal.logging.InternalLoggerFactory).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.

Error from log:
[2017-06-01T12:24:48,270][ERROR][logstash.pipeline        ] A plugin had an unrecoverable error. Will restart this plugin.
  Plugin: <LogStash::Inputs::Beats port=>5043, id=>"ee0842e64d9951495df3258d05ddacc19bf85528-3", enable_metric=>true, codec=><LogStash::Codecs::Plain id=>"plain_8db64ba9-ebec-4e05-809c-d3d456d37f45", enable_metric=>true, charset=>"UTF-8">, host=>"0.0.0.0", ssl=>false, ssl_verify_mode=>"none", include_codec_tag=>true, ssl_handshake_timeout=>10000, congestion_threshold=>5, target_field_for_codec=>"message", tls_min_version=>1, tls_max_version=>1.2, cipher_suites=>["TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384", "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384", "TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256", "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256", "TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384", "TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384", "TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256"], client_inactivity_timeout=>60>
  Error: event executor terminated

first-pipeline.conf :
input {
    beats {
        port => "5043"
    }
}

output {
        stdout { }
}

logstash.yml

path.data: /var/lib/logstash
path.config: /etc/logstash/conf.d
path.logs: /var/log/logstash


If I run logstash without beats, it works just fine.

I also uninstalled, using rpm -e, deleted all files and folders from /etc and /usr/share and then reinstalled, reconfigured and got the same error.

I checked iptables and that port is allowed and selinux is disabled.

Any other suggestions?

Some of the solutions I've researched:

https://discuss.elastic.co/t/logstash-giving-error-regarding-log4j/84767

https://discuss.elastic.co/t/how-to-configure-log4j-in-elk-statck/85236

https://github.com/logstash-plugins/logstash-input-beats/issues/132

https://github.com/logstash-plugins/logstash-input-beats/issues/193

https://discuss.elastic.co/t/warn-no-appenders-could-be-found-for-logger-org-apache-kafka-clients-producer-producerconfig/82515

https://discuss.elastic.co/t/fresh-logstash-5-2-install-gives-log4j-warnings-and-no-logging-from-plugins/75530/5

https://github.com/elastic/logstash/issues/4111

https://github.com/logstash-plugins/logstash-input-beats/issues/172
