### ISSUE TITLE
Test failure 

### ISSUE THREAD

**Issue by jakelandis** [logstash-plugins/logstash-input-beats#219]
Travis integration test failure on unrelated change.  Should investigate root cause.

```
Failures:
  1) Filebeat TLS Server verification Client verification / Mutual validation CA root intermediate create server and client certificate successfully send the events
     Got 0 failures and 3 other errors:
     Shared Example Group: "send events" called from ./spec/integration/filebeat_spec.rb:268
     1.1) Failure/Error: out, e, s = Open3.capture3(OPEN_SSL_TOPK8, :stdin_data => key.to_s)
          
          Errno::EBADF:
            Bad file descriptor - Bad file descriptor
          # ./spec/support/helpers.rb:13:in `convert_to_pkcs8'
          # ./spec/integration/filebeat_spec.rb:251:in `server_certificate_key_file_content'
          # ./spec/support/file_helpers.rb:53:in `server_certificate_key_file'
          # ./spec/integration/filebeat_spec.rb:227:in `input_config'
          # ./spec/support/integration_shared_context.rb:40:in `beats'
          # ./spec/support/integration_shared_context.rb:44:in `(root)'
          # /home/travis/.rvm/gems/jruby-1.7.25/gems/rspec-wait-0.0.9/lib/rspec/wait.rb:46:in `(root)'
     1.2) Failure/Error: @process.poll_for_exit(5)
          
          NoMethodError:
            undefined method `poll_for_exit' for nil:NilClass
          # ./spec/support/client_process_helpers.rb:23:in `stop_client'
          # ./spec/integration/filebeat_spec.rb:59:in `(root)'
          # /home/travis/.rvm/gems/jruby-1.7.25/gems/rspec-wait-0.0.9/lib/rspec/wait.rb:46:in `(root)'
     1.3) Failure/Error: LogStash::Inputs::Beats.new(input_config)
          
          LogStash::ConfigurationError:
            Something is wrong with your configuration.
          # /home/travis/build/logstash/logstash-core/lib/logstash/config/mixin.rb:114:in `config_init'
          # /home/travis/build/logstash/logstash-core/lib/logstash/inputs/base.rb:62:in `initialize'
          # ./spec/support/integration_shared_context.rb:40:in `beats'
          # ./spec/support/integration_shared_context.rb:62:in `(root)'
          # /home/travis/.rvm/gems/jruby-1.7.25/gems/rspec-wait-0.0.9/lib/rspec/wait.rb:46:in `(root)'
Finished in 6 minutes 49 seconds (files took 3.36 seconds to load)
17 examples, 1 failure, 1 pending
Failed examples:
rspec ./spec/integration/filebeat_spec.rb:261 # Filebeat TLS Server verification Client verification / Mutual validation CA root intermediate create server and client certificate successfully send the events
Randomized with seed 42375
```

Travis's log (while it lasts):
https://travis-ci.org/logstash-plugins/logstash-input-beats/jobs/240545562

Complete log preserved here:
https://gist.github.com/jakelandis/0df4d09fbdda689a276f794705e91073

Can not reproduce locally.

**Comment by jakelandis** [comment]
Failed again, different reason.

This time a Junit test failure:
```org.logstash.beats.ServerTest > testServerShouldTerminateConnectionIdleForTooLong FAILED
    java.lang.AssertionError: 
    Expected: is a numeric value within <0.1> of <3.0>
         but: <4.0> differed by <0.9>
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:8)
        at org.logstash.beats.ServerTest.testServerShouldTerminateConnectionIdleForTooLong(ServerTest.java:161)

31 tests completed, 1 failed
```
Travis log (while it lasts):
https://travis-ci.org/logstash-plugins/logstash-input-beats/jobs/240801426

Complete log preserved here:
https://gist.github.com/jakelandis/59c88468b1e83e4b030dc815720ae25e

**Comment by jakelandis** [comment]
....and Failed again, for another reason.

```
Failures:
  1) Logstash-Forwarder TLS Server Verification self signed certificate successfully send the events
     Failure/Error: try(50) { expect(queue.size).to eq(number_of_events), "Expected: #{number_of_events} got: #{queue.size}, execution output:\n #{@execution_output}" }
     
       Expected: 5 got: 0, execution output:
        2017/06/08 14:49:20.962702 	--- options -------
       2017/06/08 14:49:20.962758 	config-arg:          /tmp/studtmp-665713972257f4590a5de8ab895cc17f13a9b87ac715a158adbbc70c3812
       2017/06/08 14:49:20.962767 	idle-timeout:        5s
       2017/06/08 14:49:20.962772 	spool-size:          1024
       2017/06/08 14:49:20.962775 	harvester-buff-size: 16384
       2017/06/08 14:49:20.962779 	--- flags ---------
       2017/06/08 14:49:20.962782 	tail (on-rotation):  false
       2017/06/08 14:49:20.962786 	log-to-syslog:          false
       2017/06/08 14:49:20.962789 	quiet:             false
       2017/06/08 14:49:20.962824 {
         "network": {
           "servers": [ "localhost:21766" ],
           "ssl ca": "/tmp/studtmp-ab85d4e6faa42d437ccb6b573e685f493930449d95d9c775849c95c96379"
         },
         "files": [
           { "paths": [ "/tmp/studtmp-65326b039bbbc93a71f5d77437ee675d066ca8e2a6e114b86b8382167b97" ] }
         ]
       }
     
       2017/06/08 14:49:20.963010 Waiting for 1 prospectors to initialise
       2017/06/08 14:49:20.963048 Launching harvester on new file: /tmp/studtmp-65326b039bbbc93a71f5d77437ee675d066ca8e2a6e114b86b8382167b97
       2017/06/08 14:49:20.963096 harvest: "/tmp/studtmp-65326b039bbbc93a71f5d77437ee675d066ca8e2a6e114b86b8382167b97" (offset snapshot:0)
       2017/06/08 14:49:20.963277 All prospectors initialised with 0 states to persist
       2017/06/08 14:49:20.963371 Setting trusted CA from file: /tmp/studtmp-ab85d4e6faa42d437ccb6b573e685f493930449d95d9c775849c95c96379
       2017/06/08 14:49:20.964281 Connecting to [::1]:21766 (localhost) 
       2017/06/08 14:49:20.964424 Failure connecting to ::1: dial tcp [::1]:21766: connection refused
     Shared Example Group: "send events" called from ./spec/integration/logstash_forwarder_spec.rb:91
     # ./spec/support/integration_shared_context.rb:6:in `(root)'
     # /home/travis/.rvm/gems/jruby-1.7.25/gems/stud-0.0.22/lib/stud/try.rb:79:in `try'
     # /home/travis/.rvm/gems/jruby-1.7.25/gems/stud-0.0.22/lib/stud/try.rb:95:in `try'
     # /home/travis/.rvm/gems/jruby-1.7.25/gems/stud-0.0.22/lib/stud/try.rb:91:in `try'
     # /home/travis/.rvm/gems/jruby-1.7.25/gems/stud-0.0.22/lib/stud/try.rb:123:in `try'
     # /home/travis/.rvm/gems/jruby-1.7.25/gems/logstash-devutils-1.3.3-java/lib/logstash/devutils/rspec/logstash_helpers.rb:18:in `try'
     # ./spec/support/integration_shared_context.rb:6:in `(root)'
     # /home/travis/.rvm/gems/jruby-1.7.25/gems/rspec-wait-0.0.9/lib/rspec/wait.rb:46:in `(root)'
Finished in 8 minutes 49 seconds (files took 3.7 seconds to load)
17 examples, 1 failure, 1 pending
Failed examples:
rspec ./spec/integration/logstash_forwarder_spec.rb:90 # Logstash-Forwarder TLS Server Verification self signed certificate successfully send the events
Randomized with seed 63582
```

Travis log (while it lasts):
https://travis-ci.org/logstash-plugins/logstash-input-beats/jobs/240816614

Complete log preserved here:
https://gist.github.com/jakelandis/d5894cff25008aaa18eb0f56e66694e5

**Comment by jakelandis** [comment]
The second failure was much more pervasive (and happens first.) https://github.com/logstash-plugins/logstash-input-beats/pull/220 addresses the second failure (testServerShouldTerminateConnectionIdleForTooLong FAILED) 

I am still unable to reproduce the first error either via Travis or locally, will open a new issue if more test failures are encountered.
