### ISSUE TITLE
Unable to get ssl working between Filebeat and Logstash

### ISSUE THREAD

**Issue by lukos** [logstash-plugins/logstash-input-beats#293]
History [here](https://discuss.elastic.co/t/cannot-setup-ssl-for-filebeat-to-logstash/117785) including some of the debug output and the original full error.

I have a working filebeat to logstash pipeline with NO ssl. I wanted to enable SSL but I cannot get it to work and it is not completely clear why.

Filebeat version 6.1 for Windows 10
Logstash version 6.1 on Ubuntu 16:04
Curl running from Ubuntu 16:04

```
input {
  beats {
    port => "5044"
    ssl => true
    ssl_certificate => "/etc/ssl/certs/wildcard4-combined.cer"
    ssl_key => "/etc/ssl/private/wildcard4.pem"
  }
}
```
The cert is a commercial cert chained to a well-known root (curl is happy with it!). No changes are made in filebeat.yml from the non-ssl since I am not using client auth and have used the same port number. Filebeat shows the following error when I try and run it over ssl: "async.go:235: ERR Failed to publish events caused by: lumberjack protocol error"

If I run curl -v from another machine as suggested in setting up SSL, I get the following error: "ALPN, server did not agree to a protocol" even though the logstash debug doesn't log any error other than invalid frame (which I would expect the curl test to cause?).

This is where it gets confusing! Note all the spelling differences, some expected, some not.

Curl reports on the console that it is using ECDHE_RSA_AES_256_GCM_SHA384 however, this is not listed in nss.c, which instead says it supports TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384 (I thought that curl used nss but that might not be true). Gnu DOES support the named cipher but it has it prefixed with TLS_ according to [here](https://wiki.mozilla.org/Security/Server_Side_TLS).

* Logstash reports that it has a mapping for TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384 => ECDHE-RSA-AES256-GCM-SHA384 
* TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384 is listed as "Cipher is supported" in LS
* ECDHE-RSA-AES256-GCM-SHA384 is listed in LS "Available ciphers" when a connection is made. 
* TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384 is listed next to "Ciphers" in LS when the connection is made,
* Logstash reports HANDSHAKEN: TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384, which sounds like it should have worked.

The only thing I can possibly think right now is that in this plethora of slightly different named ciphers, there is a mapping missing or a typo? It is also possible that one of the applications in this set has been upgraded to only support some newer protocols even though the others have not?

**Comment by brianpcurran** [comment]
I'm having a very similar problem on a newly set up ELK stack.

Logstash server:

```
# cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.3 LTS"
# /usr/share/logstash/bin/logstash --version
logstash 6.1.3
# cat /etc/logstash/conf.d/00002-beats-input.conf
input {
   beats {
     port => 5044
     ssl => true
     ssl_certificate => "/etc/pki/tls/certs/logstash-forwarder.crt"
     ssl_key => "/etc/pki/tls/private/logstash-forwarder.key"
   }
}
```

Filebeat on client:

```
# cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=14.04
DISTRIB_CODENAME=trusty
DISTRIB_DESCRIPTION="Ubuntu 14.04.2 LTS"
# filebeat --version
filebeat version 6.1.3 (amd64), libbeat 6.1.3
```

Snippet of filebeat.yml:

```
output:
  logstash:
    hosts: ["log.example.local:5044"]
    bulk_max_size: 1024
    tls:
      certificate_authorities: ["/etc/pki/tls/certs/logstash-forwarder.crt"]
```

SSL verification works fine from the client using `openssl s_client`:

```
# openssl s_client -connect log.example.local:5044 -CAfile /etc/pki/tls/certs/logstash-forwarder.crt
...
---
No client certificate CA names sent
Peer signing digest: SHA256
Server Temp Key: ECDH, P-256, 256 bits
---
SSL handshake has read 1578 bytes and written 302 bytes
Verification: OK
---
New, TLSv1.2, Cipher is ECDHE-RSA-AES256-GCM-SHA384
Server public key is 2048 bit
Secure Renegotiation IS supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : ECDHE-RSA-AES256-GCM-SHA384
    Session-ID: 400FB97F0D5406C49BE9841D491BC8FA05DB6353AC01C6F27C3ED24E57D00DE6
    Session-ID-ctx:
    Master-Key: 848647F4CBDBB4648D8F4A385A4C65BC04269FECCDD2E3A53B531EB2B81A1F5C63E5CB1F2B15F00C3BB31DF1527C9647
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    Start Time: 1517847124
    Timeout   : 7200 (sec)
    Verify return code: 0 (ok)
    Extended master secret: yes
---
...
```

Starting filebeat from the command line with debug logging enabled:

```
# filebeat -c /etc/filebeat/filebeat.yml -e -v
...
2018/02/05 16:15:35.219985 log.go:85: DBG [harvester] End of file reached: /var/log/nginx/error.log; Backoff now.
2018/02/05 16:15:35.248822 log.go:85: DBG [harvester] End of file reached: /var/log/nginx/access.log; Backoff now.
2018/02/05 16:15:35.675677 output.go:92: ERR Failed to publish events: client is not connected
2018/02/05 16:15:35.675728 async.go:94: DBG [logstash] connect
2018/02/05 16:15:35.690522 async.go:142: DBG [logstash] 1024 events out of 1024 events sent to logstash host log.retroficiency.local:5044. Continue sending
2018/02/05 16:15:35.691742 async.go:235: ERR Failed to publish events caused by: lumberjack protocol error
2018/02/05 16:15:35.692038 client.go:114: DBG [transport] closing
2018/02/05 16:15:35.698902 async.go:142: DBG [logstash] 1024 events out of 1024 events sent to logstash host log.retroficiency.local:5044. Continue sending
2018/02/05 16:15:35.698934 async.go:99: DBG [logstash] close connection
2018/02/05 16:15:35.698953 async.go:99: DBG [logstash] close connection
2018/02/05 16:15:35.698977 async.go:235: ERR Failed to publish events caused by: client is not connected
2018/02/05 16:15:35.698999 logger.go:22: INFO retryer: send wait signal to consumer
2018/02/05 16:15:35.699015 logger.go:22: INFO   done
...
```

Corresponding debug log snippet from logstash:

```
[2018-02-05T16:16:33,130][INFO ][org.logstash.beats.BeatsHandler] [local: 0.0.0.0:5044, remote: 10.0.23.141:59564] Handling exception: javax.net.ssl.SSLHandshakeException: error:100000f7:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER
[2018-02-05T16:16:34,139][DEBUG][org.logstash.netty.SslSimpleBuilder] Available ciphers:[ECDHE-ECDSA-AES128-GCM-SHA256, ECDHE-RSA-AES128-GCM-SHA256, ECDHE-ECDSA-AES256-GCM-SHA384, ECDHE-RSA-AES256-GCM-SHA384, ECDHE-ECDSA-CHACHA20-POLY1305, ECDHE-RSA-CHACHA20-POLY1305, ECDHE-PSK-CHACHA20-POLY1305, ECDHE-ECDSA-AES128-SHA, ECDHE-ECDSA-AES128-SHA256, ECDHE-RSA-AES128-SHA, ECDHE-RSA-AES128-SHA256, ECDHE-PSK-AES128-CBC-SHA, ECDHE-ECDSA-AES256-SHA, ECDHE-ECDSA-AES256-SHA384, ECD
HE-RSA-AES256-SHA, ECDHE-RSA-AES256-SHA384, ECDHE-PSK-AES256-CBC-SHA, AES128-GCM-SHA256, AES256-GCM-SHA384, AES128-SHA, AES128-SHA256, PSK-AES128-CBC-SHA, AES256-SHA, AES256-SHA256, PSK-AES256-CBC-SHA, DES-CBC3-SHA]
[2018-02-05T16:16:34,139][DEBUG][org.logstash.netty.SslSimpleBuilder] Ciphers:  [TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384, TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384, TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256, TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256, TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384, TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384, TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256, TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256]
[2018-02-05T16:16:34,153][DEBUG][org.logstash.netty.SslSimpleBuilder] TLS: [TLSv1, TLSv1.1, TLSv1.2]
[2018-02-05T16:16:34,154][DEBUG][org.logstash.beats.BeatsHandler] [local: 0.0.0.0:5044, remote: 10.0.23.141:59565] Handling exception: javax.net.ssl.SSLHandshakeException: error:100000f7:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER
io.netty.handler.codec.DecoderException: javax.net.ssl.SSLHandshakeException: error:100000f7:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:459) ~[netty-all-4.1.18.Final.jar:4.1.18.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265) ~[netty-all-4.1.18.Final.jar:4.1.18.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[netty-all-4.1.18.Final.jar:4.1.18.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[netty-all-4.1.18.Final.jar:4.1.18.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[netty-all-4.1.18.Final.jar:4.1.18.Final]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1359) ~[netty-all-4.1.18.Final.jar:4.1.18.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[netty-all-4.1.18.Final.jar:4.1.18.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[netty-all-4.1.18.Final.jar:4.1.18.Final]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:935) ~[netty-all-4.1.18.Final.jar:4.1.18.Final]
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:141) ~[netty-all-4.1.18.Final.jar:4.1.18.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645) ~[netty-all-4.1.18.Final.jar:4.1.18.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580) ~[netty-all-4.1.18.Final.jar:4.1.18.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497) ~[netty-all-4.1.18.Final.jar:4.1.18.Final]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459) ~[netty-all-4.1.18.Final.jar:4.1.18.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) [netty-all-4.1.18.Final.jar:4.1.18.Final]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-all-4.1.18.Final.jar:4.1.18.Final]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_152]
Caused by: javax.net.ssl.SSLHandshakeException: error:100000f7:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER
        at io.netty.handler.ssl.ReferenceCountedOpenSslEngine.sslReadErrorResult(ReferenceCountedOpenSslEngine.java:1120) ~[netty-all-4.1.18.Final.jar:4.1.18.Final]
        at io.netty.handler.ssl.ReferenceCountedOpenSslEngine.unwrap(ReferenceCountedOpenSslEngine.java:1080) ~[netty-all-4.1.18.Final.jar:4.1.18.Final]
        at io.netty.handler.ssl.ReferenceCountedOpenSslEngine.unwrap(ReferenceCountedOpenSslEngine.java:1146) ~[netty-all-4.1.18.Final.jar:4.1.18.Final]
        at io.netty.handler.ssl.ReferenceCountedOpenSslEngine.unwrap(ReferenceCountedOpenSslEngine.java:1189) ~[netty-all-4.1.18.Final.jar:4.1.18.Final]
        at io.netty.handler.ssl.SslHandler$SslEngineType$1.unwrap(SslHandler.java:216) ~[netty-all-4.1.18.Final.jar:4.1.18.Final]
        at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1248) ~[netty-all-4.1.18.Final.jar:4.1.18.Final]
        at io.netty.handler.ssl.SslHandler.decodeNonJdkCompatible(SslHandler.java:1171) ~[netty-all-4.1.18.Final.jar:4.1.18.Final]
        at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1196) ~[netty-all-4.1.18.Final.jar:4.1.18.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:489) ~[netty-all-4.1.18.Final.jar:4.1.18.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:428) ~[netty-all-4.1.18.Final.jar:4.1.18.Final]
        ... 16 more
```

**Comment by robbavey** [comment]
@lukos Quick question - it looks like from the config you posted on the [discuss topic](https://discuss.elastic.co/t/cannot-setup-ssl-for-filebeat-to-logstash/117785) 
```
output.logstash:
  # The Logstash hosts
  hosts: ["logstash-1.internal.local:5044"]
```
that there are no `ssl` settings in your filebeat configuration file - is that correct? If there are no `ssl` settings configured, then [ssl is disabled](https://www.elastic.co/guide/en/beats/filebeat/current/configuration-ssl.html#_literal_enabled_literal_8). 

Try adding `ssl.enabled: true` to your beats configuration and see what the results are

@brianpcurran I suspect you are seeing a similar issue - your `filebeat.yml` specifies 
```
tls:
      certificate_authorities: ["/etc/pki/tls/certs/logstash-forwarder.crt"]
```

Try replacing `tls` with `ssl`

**Comment by brianpcurran** [comment]
Yep that fixed it for me!

I was using a filebeat config file from an older version and overlooked that 😞. Thank you!

**Comment by robbavey** [comment]
@lukos Can you confirm that the suggestion fixed your issue too?

**Comment by robbavey** [comment]
Closing this issue - @lukos, feel free to reopen if the suggestion above does not solve your issue

**Comment by lukos** [comment]
Yes, this worked for me thanks. 

I think searching for ELK stuff is a bit fraught because I easily find myself on very old versions which obviously don't have the correct information. I'm not sure if the elastic site could update robots or something to stop Google returning anything on old versions in the search results? Maybe it's just me :-)

**Comment by rishiloyola** [comment]
@robbavey It's not working for me.

**Logstash config:**
```
input {
	beats {
    		port => 5044
    		ssl => true
        ssl_certificate => "/etc/pki/tls/certs/logstash-forwarder.crt"
        ssl_key => "/etc/pki/tls/private/logstash-forwarder.key"
  	}
}

## Add your filters / logstash plugins configuration here
filter {
  	if [type] == "syslog" {
    	grok {
      		match => { "message" => "%{SYSLOGTIMESTAMP:syslog_timestamp} %{SYSLOGHOST:syslog_hostname} %{DATA:syslog_program}(?:\[%{POSINT:syslog_pid}\])?: %{GREEDYDATA:syslog_message}" }
      		add_field => [ "received_at", "%{@timestamp}" ]
      		add_field => [ "received_from", "%{host}" ]
    	}
    	syslog_pri { }
    	date {
      		match => [ "syslog_timestamp", "MMM  d HH:mm:ss", "MMM dd HH:mm:ss" ]
    	}
    }
}


output {
	elasticsearch {
		hosts => "127.0.0.1:9200"
		sniffing => true
    	manage_template => false
    	index => "%{[@metadata][beat]}-%{+YYYY.MM.dd}"
    	document_type => "%{[@metadata][type]}"
	}
}
```

**Filebeat config:**
```
filebeat:
	  prospectors:
	    -
	      paths:
	        - /var/log/auth.log
	        - /var/log/syslog

	      input_type: log
	      
	      document_type: syslog

	  registry_file: /var/lib/filebeat/registry

	output:
	  logstash:
	    hosts: ["$1:5044"]
	    bulk_max_size: 1024
		ssl:
			enabled: true
			certleificate_authorities: ["/etc/pki/tls/certs/logstash-forwarder.crt"]
	shipper:

	logging:
	  files:
	    rotateeverybytes: 10485760 # = 10MB
```

**Error:**
```
[2018-12-13T00:36:06,229][INFO ][org.logstash.beats.BeatsHandler] [local: 0.0.0.0:5044, remote: 54.243.8.44:53086] Handling exception: javax.net.ssl.SSLHandshakeException: error:100000f7:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER
[2018-12-13T00:36:06,229][WARN ][io.netty.channel.DefaultChannelPipeline] An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
io.netty.handler.codec.DecoderException: javax.net.ssl.SSLHandshakeException: error:100000f7:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:459) ~[netty-all-4.1.18.Final.jar:4.1.18.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265) ~[netty-all-4.1.18.Final.jar:4.1.18.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[netty-all-4.1.18.Final.jar:4.1.18.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[netty-all-4.1.18.Final.jar:4.1.18.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[netty-all-4.1.18.Final.jar:4.1.18.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1359) ~[netty-all-4.1.18.Final.jar:4.1.18.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[netty-all-4.1.18.Final.jar:4.1.18.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[netty-all-4.1.18.Final.jar:4.1.18.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:935) ~[netty-all-4.1.18.Final.jar:4.1.18.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:141) ~[netty-all-4.1.18.Final.jar:4.1.18.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645) ~[netty-all-4.1.18.Final.jar:4.1.18.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580) ~[netty-all-4.1.18.Final.jar:4.1.18.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497) ~[netty-all-4.1.18.Final.jar:4.1.18.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459) [netty-all-4.1.18.Final.jar:4.1.18.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) [netty-all-4.1.18.Final.jar:4.1.18.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-all-4.1.18.Final.jar:4.1.18.Final]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
Caused by: javax.net.ssl.SSLHandshakeException: error:100000f7:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER
	at io.netty.handler.ssl.ReferenceCountedOpenSslEngine.sslReadErrorResult(ReferenceCountedOpenSslEngine.java:1120) ~[netty-all-4.1.18.Final.jar:4.1.18.Final]
	at io.netty.handler.ssl.ReferenceCountedOpenSslEngine.unwrap(ReferenceCountedOpenSslEngine.java:1080) ~[netty-all-4.1.18.Final.jar:4.1.18.Final]
	at io.netty.handler.ssl.ReferenceCountedOpenSslEngine.unwrap(ReferenceCountedOpenSslEngine.java:1146) ~[netty-all-4.1.18.Final.jar:4.1.18.Final]
	at io.netty.handler.ssl.ReferenceCountedOpenSslEngine.unwrap(ReferenceCountedOpenSslEngine.java:1189) ~[netty-all-4.1.18.Final.jar:4.1.18.Final]
	at io.netty.handler.ssl.SslHandler$SslEngineType$1.unwrap(SslHandler.java:216) ~[netty-all-4.1.18.Final.jar:4.1.18.Final]
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1248) ~[netty-all-4.1.18.Final.jar:4.1.18.Final]
	at io.netty.handler.ssl.SslHandler.decodeNonJdkCompatible(SslHandler.java:1171) ~[netty-all-4.1.18.Final.jar:4.1.18.Final]
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1196) ~[netty-all-4.1.18.Final.jar:4.1.18.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:489) ~[netty-all-4.1.18.Final.jar:4.1.18.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:428) ~[netty-all-4.1.18.Final.jar:4.1.18.Final]
	... 16 more
```

**Note:** I am using self signed certificate for it. 
Command to generate certificate:
```shell
sudo openssl req -config /etc/ssl/openssl.cnf -x509 -days 3650 -batch -nodes -newkey rsa:2048 -keyout private/logstash-forwarder.key -out certs/logstash-forwarder.crt
```

**Comment by shiftux** [comment]
i have the same error as @rishiloyola 
although the logs are transmitted and visible in kibana, still i don't like having the error in logstash
any update?

**Comment by rishiloyola** [comment]
@shiftux It is working based on peer-to-peer tls. Follow these steps to generate fake tls certs. 

https://gist.github.com/rishiloyola/79f869749bf54d135f7f6fe61e0e99a7

**Comment by shiftux** [comment]
yup, found out that `ssl_verify_mode => "force_peer"` led to the `WRONG_VERSION_NUMBER` error.
the `ssl_verify_mode => "peer"` option works.

**Comment by KrisRoofe** [comment]
Refer to this SO post [Failed to connect to backoff(async(tcp://ip:5044)): dial tcp ip:5044: i/o timeout](https://stackoverflow.com/q/57635755/6521116)
