### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by ruflin** [logstash-plugins/logstash-input-beats#3]
When I run Filebeat -> LS -> after some time error messages start to pop up. It seems like all log messages are read until the following error pops up. The error is from then on repeated multiple times (every x seconds):

```
Beats input: unhandled exception {:exception=>#<ZeroDivisionError: divided by 0>, :backtrace=>["org/jruby/RubyFixnum.java:632:in `%'", "/Users/ruflin/Dev/test-setup/logstash-1.5.4/vendor/bundle/jruby/1.9/gems/logstash-input-beats-0.9.1/lib/lumberjack/beats/server.rb:421:in `ack?'", "/Users/ruflin/Dev/test-setup/logstash-1.5.4/vendor/bundle/jruby/1.9/gems/logstash-input-beats-0.9.1/lib/lumberjack/beats/server.rb:362:in `ack_if_needed'", "/Users/ruflin/Dev/test-setup/logstash-1.5.4/vendor/bundle/jruby/1.9/gems/logstash-input-beats-0.9.1/lib/lumberjack/beats/server.rb:345:in `read_socket'", "/Users/ruflin/Dev/test-setup/logstash-1.5.4/vendor/bundle/jruby/1.9/gems/logstash-input-beats-0.9.1/lib/lumberjack/beats/server.rb:246:in `json_data_payload'", "/Users/ruflin/Dev/test-setup/logstash-1.5.4/vendor/bundle/jruby/1.9/gems/logstash-input-beats-0.9.1/lib/lumberjack/beats/server.rb:163:in `feed'", "/Users/ruflin/Dev/test-setup/logstash-1.5.4/vendor/bundle/jruby/1.9/gems/logstash-input-beats-0.9.1/lib/lumberjack/beats/server.rb:296:in `compressed_payload'", "/Users/ruflin/Dev/test-setup/logstash-1.5.4/vendor/bundle/jruby/1.9/gems/logstash-input-beats-0.9.1/lib/lumberjack/beats/server.rb:163:in `feed'", "/Users/ruflin/Dev/test-setup/logstash-1.5.4/vendor/bundle/jruby/1.9/gems/logstash-input-beats-0.9.1/lib/lumberjack/beats/server.rb:330:in `read_socket'", "/Users/ruflin/Dev/test-setup/logstash-1.5.4/vendor/bundle/jruby/1.9/gems/logstash-input-beats-0.9.1/lib/lumberjack/beats/server.rb:315:in `run'", "/Users/ruflin/Dev/test-setup/logstash-1.5.4/vendor/bundle/jruby/1.9/gems/logstash-input-beats-0.9.1/lib/logstash/inputs/beats.rb:150:in `invoke'", "org/jruby/RubyProc.java:271:in `call'", "/Users/ruflin/Dev/test-setup/logstash-1.5.4/vendor/bundle/jruby/1.9/gems/concurrent-ruby-0.9.1-java/lib/concurrent/executor/executor_service.rb:515:in `run'", "Concurrent$$JavaExecutorService$$Job_379996920.gen:13:in `run'"], :level=>:error}
```

Versions:
* Filebeat 1.0.0-beta4
* Logstash 1.5.4
* Elasticsearch 1.7.2

**Comment by ph** [comment]
Fixed in #4
