### ISSUE TITLE
TLS 1.2 Ciphers Unavailable

### ISSUE THREAD

**Issue by robgil** [logstash-plugins/logstash-input-beats#324]
Please post all product and debugging questions on our [forum](https://discuss.elastic.co/c/logstash). Your questions will reach our wider community members there, and if we confirm that there is a bug, then we can open a new issue here.

For all general issues, please provide the following details for fast resolution:

- Version: 5.0.16, LS 6.2.4
- Operating System: OSX
- Config File (if you have sensitive info, please remove it):

_filebeat.conf_
```
input {
  beats {
    port => 5044
    host => '127.0.0.1'
    ssl => true
    ssl_certificate => "<cert>"
    ssl_certificate_authorities => ["<ca bundle>"]
    ssl_key => "<key>"
    ssl_verify_mode => 'force_peer'
    tls_min_version => '1.2'
    cipher_suites => ['ECDHE-RSA-AES-128-GCM-SHA256', 'ECDHE-ECDSA-AES-128-GCM-SHA256', 'ECDHE-RSA-AES-256-GCM-SHA384', 'ECDHE-ECDSA-AES-256-GCM-SHA384']
  }
}

filter {
}

output {
  stdout { codec => rubydebug { metadata => true } }
}
```

- Sample Data:
Any, happens on startup.

- Error:
```
[2018-06-08T12:55:12,545][ERROR][logstash.pipeline        ] Pipeline aborted due to error {:pipeline_id=>"main", :exception=>#<LogStash::ConfigurationError: Cipher `ECDHE-RSA-AES-128-GCM-SHA256` is not available>, :backtrace=>["/usr/local/Cellar/logstash/6.2.4/libexec/vendor/bundle/jruby/2.3.0/gems/logstash-input-beats-5.0.16-java/lib/logstash/inputs/beats.rb:170:in `create_server'", "/usr/local/Cellar/logstash/6.2.4/libexec/vendor/bundle/jruby/2.3.0/gems/logstash-input-beats-5.0.16-java/lib/logstash/inputs/beats.rb:158:in `register'", "/usr/local/Cellar/logstash/6.2.4/libexec/logstash-core/lib/logstash/pipeline.rb:342:in `register_plugin'", "/usr/local/Cellar/logstash/6.2.4/libexec/logstash-core/lib/logstash/pipeline.rb:353:in `block in register_plugins'", "org/jruby/RubyArray.java:1734:in `each'", "/usr/local/Cellar/logstash/6.2.4/libexec/logstash-core/lib/logstash/pipeline.rb:353:in `register_plugins'", "/usr/local/Cellar/logstash/6.2.4/libexec/logstash-core/lib/logstash/pipeline.rb:500:in `start_inputs'", "/usr/local/Cellar/logstash/6.2.4/libexec/logstash-core/lib/logstash/pipeline.rb:394:in `start_workers'", "/usr/local/Cellar/logstash/6.2.4/libexec/logstash-core/lib/logstash/pipeline.rb:290:in `run'", "/usr/local/Cellar/logstash/6.2.4/libexec/logstash-core/lib/logstash/pipeline.rb:250:in `block in start'"], :thread=>"#<Thread:0x5fe9f744 run>"}
[2018-06-08T12:55:12,589][ERROR][logstash.agent           ] Failed to execute action {:id=>:main, :action_type=>LogStash::ConvergeResult::FailedAction, :message=>"Could not execute action: LogStash::PipelineAction::Create/pipeline_id:main, action_result: false", :backtrace=>nil}
```

- Steps to Reproduce:
Configure `logstash-input-beats` for TLS 1.2 using the cipher suites from [beats](https://www.elastic.co/guide/en/logstash/current/plugins-inputs-beats.html#plugins-inputs-beats-cipher_suites) and attempt to start up. 

`logstash -f filebeat.conf --debug`

**Comment by robgil** [comment]
This was due to a difference in naming between beats (written in Go) and Logstash (which uses Netty upstream). Netty's definitions are [here](https://github.com/netty/netty/blob/4.1/handler/src/main/java/io/netty/handler/ssl/SslUtils.java). 

On the logstash side, ciphers for TLS 1.2 should look like this per the [beats](https://www.elastic.co/guide/en/beats/filebeat/current/configuration-ssl.html#_literal_cipher_suites_literal) recommendations for 1.2.
```
    cipher_suites => ['TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256', 'TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256', 'TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384', 'TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384']
```
