### ISSUE TITLE
unhanded exception - unsupported protocol 60

### ISSUE THREAD

**Issue by schmandforke** [logstash-plugins/logstash-input-beats#35]
Hey there,

i got an unusual exception and don't know what todo:

` ` ` 
Beats input: unhandled exception {:exception=>#<RuntimeError: unsupported protocol 60>, :backtrace=>["/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-beats-2.0.3/lib/lumberjack/beats/server.rb:225:in `handle_version'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-beats-2.0.3/lib/lumberjack/beats/server.rb:210:in `header'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-beats-2.0.3/lib/lumberjack/beats/server.rb:163:in `feed'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-beats-2.0.3/lib/lumberjack/beats/server.rb:342:in `read_socket'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-beats-2.0.3/lib/lumberjack/beats/server.rb:319:in `run'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-beats-2.0.3/lib/logstash/inputs/beats.rb:184:in `invoke'", "org/jruby/RubyProc.java:281:in `call'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/concurrent-ruby-0.9.2-java/lib/concurrent/executor/executor_service.rb:515:in `run'", "Concurrent$$JavaExecutorService$$Job_463958253.gen:13:in `run'"], :level=>:error}
```

my filbeat config looks like this:

```
filebeat:
  prospectors:
    -
      paths:
        - /var/log/*.log
      input_type: log
output:
  logstash:
    enabled: true
    hosts:
      - logstash01.xxx.com:5522
```

and my logstash config is this:

```
input {
  beats {
    type  => "my_events"
    port  => "5522"
  }
}
filter {
  ...
}
output {
  ...
}
```

would be great if somebody can help me... i don't see what is wrong... 

My Setup is:

elasticsearch (3 nodes) => version 2.1.0-1
logstash (2 nodes) => version 2.1.1-1
kibana ( 1 node) => version 4.3.0
filebeat => version 1.0.0

Thanks

**Comment by urso** [comment]
Is some other service using this port? This error occurs on very first byte read from socket. Check for TCP connections using ss, netstat or lsof.

**Comment by ph** [comment]
@schmandforke Anything else is trying to connect to the same port? like @urso said this error is generated from the first few bytes read from the socket.

**Comment by davgibney1** [comment]
{:timestamp=>"2016-01-04T11:28:19.191000-0500", :message=>"Beats input: unhandled exception", :exception=>#<RuntimeError: unsupported protocol 72>, :backtrace=>["/opt/logstash-2.1.1/vendor/bundle/jruby/1.9/gems/logstash-input-beats-2.0.3/lib/lumberjack/beats/server.rb:225:in `handle_version'", "/opt/logstash-2.1.1/vendor/bundle/jruby/1.9/gems/logstash-input-beats-2.0.3/lib/lumberjack/beats/server.rb:210:in `header'", "/opt/logstash-2.1.1/vendor/bundle/jruby/1.9/gems/logstash-input-beats-2.0.3/lib/lumberjack/beats/server.rb:163:in `feed'", "/opt/logstash-2.1.1/vendor/bundle/jruby/1.9/gems/logstash-input-beats-2.0.3/lib/lumberjack/beats/server.rb:342:in `read_socket'", "/opt/logstash-2.1.1/vendor/bundle/jruby/1.9/gems/logstash-input-beats-2.0.3/lib/lumberjack/beats/server.rb:319:in `run'", "/opt/logstash-2.1.1/vendor/bundle/jruby/1.9/gems/logstash-input-beats-2.0.3/lib/logstash/inputs/beats.rb:184:in `invoke'", "org/jruby/RubyProc.java:281:in `call'", "/opt/logstash-2.1.1/vendor/bundle/jruby/1.9/gems/concurrent-ruby-0.9.2-java/lib/concurrent/executor/executor_service.rb:515:in `run'", "Concurrent$$JavaExecutorService$$Job_754842357.gen:13:in `run'"], :level=>:error}

**Comment by davgibney1** [comment]
If I comment out the logstash stuff from the filebeat config, then elasticsearch is able to receive the logs OK. Seems like there is a problem with logstash, and/or a problem with filebeat in terms of logstash.

**Comment by dedemorton** [comment]
Your Filebeat config is old. It uses the "enabled" option, which was removed before the official Beats 1.0 release.  The correct format is documented here: 
https://www.elastic.co/guide/en/beats/filebeat/current/filebeat-getting-started.html#_configuring_filebeat_to_use_logstash

output:
  logstash:
    hosts: ["127.0.0.1:5044"]

You also need to disable the elasticsearch output by commenting it out. 

Also, m ake sure that you set up logstash correctly: 
https://www.elastic.co/guide/en/beats/libbeat/1.0.1/getting-started.html#logstash-setup
