### ISSUE TITLE
When running the tests inside logstash

### ISSUE THREAD

**Issue by ph** [logstash-plugins/logstash-input-beats#48]
This test was failling when we were running all the plugins tests under logtash.
```
1) LogStash::Filters::Date fill next year if january events arrive in december "Jan 01 01:00:00" when processed
     Failure/Error: Unable to find matching line from backtrace
     NoMethodError:
       undefined method `now' for Time:Class
     # ./vendor/bundle/jruby/1.9/gems/logstash-input-beats-2.1.2/lib/logstash/inputs/beats_support/circuit_breaker.rb:93:in `state'
     # ./vendor/bundle/jruby/1.9/gems/logstash-input-beats-2.1.2/lib/logstash/inputs/beats_support/circuit_breaker.rb:60:in `closed?'
     # ./vendor/bundle/jruby/1.9/gems/logstash-input-beats-2.1.2/lib/logstash/inputs/beats.rb:126:in `run'
     # ./vendor/bundle/jruby/1.9/gems/logstash-input-beats-2.1.2/spec/inputs/beats_spec.rb:93:in `(root)'
```

**Comment by ph** [comment]
We don't actually mock or stub any time in this plugins I am wondering if its actually this can be generated from another plugins.

**Comment by ph** [comment]
I know why, the thread is probably still running when the date filter test run.
