### ISSUE TITLE
IdentityMapCodec has reached 100% capacity

### ISSUE THREAD

**Issue by hrchu** [logstash-plugins/logstash-input-beats#66]
logstash 2.2.2
filebeat 1.1.2
arch: filebeat=>logstash=>elasticsearch

logstash continually output the following error message, and log cannot be write to elasticsearch.

```
{:timestamp=>"2016-03-28T13:48:10.861000+0800", :message=>"IdentityMapCodec has reached 100% capacity", :current_size=>20000, :upper_limit=>20000, :level=>:error}
{:timestamp=>"2016-03-28T13:48:10.862000+0800", :message=>"Beats input: unhandled exception", :exception=>#<LogStash::Codecs::IdentityMapCodec::IdentityMapUpperLimitException: LogStash::Codecs::IdentityMapCodec::IdentityMapUpperLimitException>, :backtrace=>["/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-codec-multiline-2.0.9/lib/logstash/codecs/identity_map_codec.rb:37:in `visit'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-codec-multiline-2.0.9/lib/logstash/codecs/identity_map_codec.rb:325:in `check_map_limits'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-codec-multiline-2.0.9/lib/logstash/codecs/identity_map_codec.rb:304:in `record_codec_usage'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-codec-multiline-2.0.9/lib/logstash/codecs/identity_map_codec.rb:295:in `stream_codec'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-codec-multiline-2.0.9/lib/logstash/codecs/identity_map_codec.rb:177:in `accept'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-beats-2.1.3/lib/logstash/inputs/beats_support/connection_handler.rb:58:in `process'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-beats-2.1.3/lib/logstash/inputs/beats_support/connection_handler.rb:33:in `accept'", "org/jruby/RubyProc.java:281:in `call'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-beats-2.1.3/lib/lumberjack/beats/server.rb:429:in `data'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-beats-2.1.3/lib/lumberjack/beats/server.rb:408:in `read_socket'", "org/jruby/RubyProc.java:281:in `call'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-beats-2.1.3/lib/lumberjack/beats/server.rb:420:in `ack_if_needed'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-beats-2.1.3/lib/lumberjack/beats/server.rb:404:in `read_socket'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-beats-2.1.3/lib/lumberjack/beats/server.rb:261:in `json_data_payload'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-beats-2.1.3/lib/lumberjack/beats/server.rb:178:in `feed'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-beats-2.1.3/lib/lumberjack/beats/server.rb:311:in `compressed_payload'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-beats-2.1.3/lib/lumberjack/beats/server.rb:178:in `feed'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-beats-2.1.3/lib/lumberjack/beats/server.rb:389:in `read_socket'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-beats-2.1.3/lib/lumberjack/beats/server.rb:369:in `run'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-beats-2.1.3/lib/logstash/inputs/beats_support/connection_handler.rb:33:in `accept'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-beats-2.1.3/lib/logstash/inputs/beats.rb:177:in `handle_new_connection'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-beats-2.1.3/lib/logstash/inputs/beats_support/circuit_breaker.rb:4
2:in `execute'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-beats-2.1.3/lib/logstash/inputs/beats.rb:177:in `handle_new_connection'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-beats-2.1.3/lib/logstash/inputs/beats.rb:133:in `run'"], :level=>:error}
```

How to fix this?
Thanks

**Comment by ph** [comment]
Oh, this should happen too often and the identity should be cleared.
Can you give a bit more information on your configuration?

- How many clients connected to logtash
- How many files are watched by filebeat?
- Can you dump a **heap dump** of the logstash process when this situation occur and attach it to this issue? using jmap, `jmap  -dump:file=memory.heap <PROCESS PID>`

Usually the IdentityMap should clear unused identity stream after some time, but from your message this doesn`t seems to be the case. I am really interested in the content of the memory.

**Comment by ph** [comment]
I've seen this problem in another use case, but the environment was bigger than yours, +500 filebeat with 40 files on each server.

@hrchu Are you using the multiline filter?  Can you share your configuration?

**Comment by hrchu** [comment]
@ph no multiline filter. Here is my config: https://gist.github.com/hrchu/20e08343121830ff7c6a54324811d219

**Comment by ph** [comment]
@hrchu Would you mind adding a heap dump to this issue?
