### ISSUE TITLE
Failling tests

### ISSUE THREAD

**Issue by ph** [logstash-plugins/logstash-input-beats#69]
http://build-eu-1.elasticsearch.org/job/logstash-plugin-input-beats-unit/jdk=JDK8,nodes=metal-pool/lastBuild/console

```
  27) LogStash::Inputs::BeatsSupport::EventTransformCommon when the `beat.hostname` exist in the event when `host` key exists on the event doesn't override it
     Failure/Error: i.register
     NoMethodError:
       undefined method `value' for nil:NilClass
     # ./lib/logstash/inputs/beats.rb:113:in `register'
     # ./spec/support/shared_examples.rb:14:in `input'
     # ./spec/support/shared_examples.rb:13:in `input'
     # ./spec/inputs/beats_support/event_transform_common_spec.rb:8:in `subject'
     # ./spec/support/shared_examples.rb:52:in `(root)'

  28) LogStash::Inputs::BeatsSupport::EventTransformCommon when the `beat.hostname` exist in the event when `host` key doesn't exist on the event copy the `beat.hostname` to `host` or backward compatibility
     Failure/Error: i.register
     NoMethodError:
       undefined method `value' for nil:NilClass
     # ./lib/logstash/inputs/beats.rb:113:in `register'
     # ./spec/support/shared_examples.rb:14:in `input'
     # ./spec/support/shared_examples.rb:13:in `input'
     # ./spec/inputs/beats_support/event_transform_common_spec.rb:8:in `subject'
     # ./spec/support/shared_examples.rb:43:in `(root)'

  29) LogStash::Inputs::BeatsSupport::EventTransformCommon when the `beast.hotname` doesnt exist on the event doesnt change the value
     Failure/Error: i.register
     NoMethodError:
       undefined method `value' for nil:NilClass
     # ./lib/logstash/inputs/beats.rb:113:in `register'
     # ./spec/support/shared_examples.rb:14:in `input'
     # ./spec/support/shared_examples.rb:13:in `input'
     # ./spec/inputs/beats_support/event_transform_common_spec.rb:8:in `subject'
     # ./spec/support/shared_examples.rb:33:in `(root)'

Finished in 46.71 seconds (files took 2.73 seconds to load)
122 examples, 29 failures, 5 pending

Failed examples:

```

**Comment by ph** [comment]
fixed in #68
