### ISSUE TITLE
Running out of FD make hilarous things happen

### ISSUE THREAD

**Issue by ph** [logstash-plugins/logstash-input-beats#98]
Make it more resilient when we run out of FD.

```
10000.times.collect { TCPSocket.new("localhost", 12345) }.map(&:close)
```

**Comment by ph** [comment]
moved from https://github.com/logstash-plugins/logstash-input-beats/pull/93

**Comment by ph** [comment]
@jordansissel What would be the best way to fail here? The solution is just increasing file descriptor.

**Comment by ph** [comment]
I've did some research and experimentation on this topic, I've seen java fails in really weird ways when it happen.

So not sure we can provide a nice way to reject connection, but we could do the following:

- Add a new handler in the channel pipeline
- The new handler will check the limit of the FD when a new connection occur
- Using a threshold it could yield a warning on new connection in the log.

I am a bit concerned of adding this kind of warning but maybe its the good solution here? WDYT?

Now lets read some funny traces:

```
15:41:17.053 [main] INFO  org.logstash.beats.Server - Starting server on port: 5044
Exception in thread "nioEventLoopGroup-2-1" java.lang.InternalError: java.io.FileNotFoundException: /Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/jre/lib/ext/cldrdata.jar (Too many open files in system)
	at sun.misc.URLClassPath$JarLoader.getResource(URLClassPath.java:1003)
	at sun.misc.URLClassPath.getResource(URLClassPath.java:212)
```

**Comment by jordansissel** [comment]
@ph indeed! I got similar very very weird traces when running out of file descriptors. I wonder if we can somehow set the maximum number of connections for the input to be something like 80% of the file descriptor limit? It might be a good first step.

**Comment by ph** [comment]
@jordansissel Yeah its worth investigating, I've look deep inside the netty framework yesterday and I haven't found where to change that kind of behavior I believe its much higher than the `ChannelHandler`.

Because when we are in the `ChannelHandler` the accept loop has already kick in and got stopped by the FD issues.

I will give another go next week, I will remove the 5.0.0 label for that and mark it as enhancement, WDYT?
