### ISSUE TITLE
Sending a MAX_INT as the json payload length cause the parser to throw an exception

### ISSUE THREAD

**Issue by ph** [logstash-plugins/logstash-input-beats#99]
Sending a MAX_INT as the json payload length causes fun errors

Reproduction:

```
>> o = { "hello" => "world" }; TCPSocket.new("localhost", 12345).tap { |x| x.write(["1W", 1].pack("A*N")); x.write(["2J", 1, -1, o.to_json].pack("A*NNA*")); }.close
```

full output
```
15:19:36.794 [nioEventLoopGroup-3-2] ERROR org.logstash.beats.BeatsHandler - Exception
io.netty.handler.codec.DecoderException: java.lang.NegativeArraySizeException
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:442) ~[netty-all-4.1.1.Final.jar:4.1.1.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:248) ~[netty-all-4.1.1.Final.jar:4.1.1.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-all-4.1.1.Final.jar:4.1.1.Final]
        at io.netty.channel.AbstractChannelHandlerContext.access$600(AbstractChannelHandlerContext.java:36) [netty-all-4.1.1.Final.jar:4.1.1.Final]
        at io.netty.channel.AbstractChannelHandlerContext$7.run(AbstractChannelHandlerContext.java:339) [netty-all-4.1.1.Final.jar:4.1.1.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:339) [netty-all-4.1.1.Final.jar:4.1.1.Final]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:393) [netty-all-4.1.1.Final.jar:4.1.1.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:742) [netty-all-4.1.1.Final.jar:4.1.1.Final]
        at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:145) [netty-all-4.1.1.Final.jar:4.1.1.Final]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_72]
Caused by: java.lang.NegativeArraySizeException
        at org.logstash.beats.BeatsParser.decode(BeatsParser.java:193) ~[logstash-input-beats-3.1.0.beta1.jar:?]
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:411) ~[netty-all-4.1.1.Final.jar:4.1.1.Final]
        ... 9 more
```

**Comment by ph** [comment]
One things is weird in the send data `1W` should be `2W`.

I havent tested it, maybe the state machien is trying to parse a v1 frame and not a json frame.

**Comment by ph** [comment]
V1 Frame have also the same problem if you send a negative fields, so I've changed both of these part to assert an integer.

It will make the parse more robust overall, even if the case should really occur.
